image: docker:latest

services: ["docker:dind"]
stages: [build]

build-and-push:
  before_script: [docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY]
  stage: build
  when: manual
  script: 
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE